name: idealsol
description: "A new Flutter project."
# Prevents accidental publication to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Defines version and build number.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  syncfusion_flutter_charts: ^28.1.33
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Hoog0555
      fonts:
        - asset: Fonts/hoog0555.ttf
